{"uuid": "cd3301db-a1ae-4efc-b0fe-d63eb36f1083", "children": ["7df2734c-9f9b-4935-8cec-b224760651e3", "a36beeb3-886d-444e-bac6-cc81b0740697", "c09ba079-24cd-4b67-b7c8-27efdcecebd2", "15685507-a965-4d82-b645-9f7beb7ebaea"], "befores": [{"name": "test_logsystem", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"E:\\测试软件\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\吾之梦\\PycharmProjects\\untitled1\\iwebsns\\testcases\\conftest.py\", line 8, in test_logsystem\n    browser = webdriver.Firefox(executable_path=driver_path)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 170, in __init__\n    RemoteWebDriver.__init__(\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1629034616567, "stop": 1629034623944}], "start": 1629034616567, "stop": 1629034624275}