{"uuid": "d84af0a7-a960-41ba-b6ed-50a310419705", "children": ["c7571e32-ce95-40a8-ba93-98ec2b1c1c74"], "befores": [{"name": "test_logsystem", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"E:\\测试软件\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\吾之梦\\PycharmProjects\\untitled1\\iwebsns\\testcases\\conftest.py\", line 8, in test_logsystem\n    browser = webdriver.Firefox(executable_path=driver_path)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 170, in __init__\n    RemoteWebDriver.__init__(\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\测试软件\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1628828310862, "stop": 1628828316111}], "start": 1628828310862, "stop": 1628828316286}